{
    "functionName": "test_data_in_repo_succeeds_directories_not_found",
    "className": null,
    "fileName": "/devmanorg_&_fiasko_bro/tests_&_test_general_validators_&_test_has_no_directories_from_blacklist.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "output = validators.data_in_repo(project_folder=test_repo, data_directories\n    =['the_name_of_data_dir_01236'])\nassert output is None\n"
}