{
    "functionName": "test_bug_2671682",
    "className": "test_MySQLdb",
    "fileName": "/anthill-utils_&_PyMySQL/pymysql_&_tests_&_thirdparty_&_test_MySQLdb_&_test_MySQLdb_capabilities.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "from pymysql.constants import ER\ntry:\n    self.cursor.execute('describe some_non_existent_table')\nexcept self.connection.ProgrammingError as msg:\n    self.assertEqual(msg.args[0], ER.NO_SUCH_TABLE)\n"
}