{
    "functionName": "test_step_generator_start_stop_exception",
    "className": "TestStepGenerator",
    "fileName": "/alsprogrammer_&_PythonFuzzyLogic/tests_&_defuzzify_test.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "sum = 0\nwith self.assertRaises(ValueError) as context:\n    step_generator(0, 1, 0).__next__()\nself.assertTrue(isinstance(context.exception, ValueError))\n"
}