{
    "functionName": "test_connect_stops_on_reaching_max_retries",
    "className": null,
    "fileName": "/VinayGValsaraj_&_PyAPNs23/test_&_test_client.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "mock_connection.connect.side_effect = [RuntimeError] * 4\nwith pytest.raises(ConnectionFailed):\n    client.connect()\nassert mock_connection.connect.call_count == 3\n"
}