{
    "functionName": "test_invalid_reason_can_be_setted_and_getted",
    "className": null,
    "fileName": "/Rambatino_&_CHAID/tests_&_test_split.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "\"\"\" Test that invalid reasons can be set and accessed on a split instance \"\"\"\nsplit = CHAID.Split('a', None, None, 1, 0)\nreason = CHAID.InvalidSplitReason.ALPHA_MERGE\nsplit.invalid_reason = reason\nassert split.invalid_reason == reason, 'Splits should be able to store invalid reasons'\n"
}