{
    "functionName": "test_departures_error_server",
    "className": null,
    "fileName": "/cgtobi_&_PyRMVtransport/tests_&_test_rmvtransport.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "\"\"\"Test server error handling.\"\"\"\nasync with aresponses.ResponsesMockServer(loop=event_loop) as arsps:\n    arsps.add(URL, URL_PATH, 'get', aresponses.Response(text='error',\n        status=500))\n    async with aiohttp.ClientSession(loop=event_loop) as session:\n        rmv = RMVtransport(session)\n        station_id = '3006904'\n        await rmv.get_departures(station_id)\npytest.mark.asynciopytest.mark.xfail(raises=RMVtransportError)"
}