{
    "functionName": "test_syntax_error_shows_up",
    "className": null,
    "fileName": "/devmanorg_&_fiasko_bro/tests_&_test_validation_interface_&_test_syntax_errors_handled_properly.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "expected_output = [('syntax_error', 'file_with_syntax_error.py')]\noutput = validate(syntax_error_repo)\nassert output == expected_output\n"
}