{
    "functionName": "test_default_error_msg_with_kwargs",
    "className": "PyU4VUtilsTest",
    "fileName": "/MichaelMcAleer_&_PyU4V/PyU4V_&_tests_&_unit_tests_&_test_pyu4v_utils.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "class FakePyU4VException(exception.PyU4VException):\n    message = 'default message: %(code)s'\nexc = FakePyU4VException(code=500)\nself.assertEqual('default message: 500', six.text_type(exc))\n"
}