{
    "functionName": "test_bad_df_columns_2",
    "className": "CleanDFOrSeriesTestCase",
    "fileName": "/mzy2240_&_ESA/tests_&_test_saw.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "\"\"\"This time, use upper-case so we don't get an index error.\"\"\"\nbad_df = pd.DataFrame([[1, 'bleh']], columns=['BusNum', 'Bleh'])\nwith self.assertRaisesRegex(ValueError, 'The given object has fields'):\n    saw_14.clean_df_or_series(obj=bad_df, ObjectType='gen')\n"
}