{
    "functionName": "test_should_raise_error_if_model_not_fit_to_data_yet",
    "className": "DataGeneratorTest",
    "fileName": "/thoughtworksarts_&_EmoPy/EmoPy_&_tests_&_unittests_&_test_data_generator.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "with self.assertRaises(ValueError) as a:\n    DataGenerator(time_delay=5).get_next_batch()\nwith self.assertRaises(ValueError) as b:\n    DataGenerator(time_delay=5).generate()\nself.assertEqual('Model is not fit to any data set yet', str(a.exception))\nself.assertEqual('Model is not fit to any data set yet', str(b.exception))\n"
}