{
    "functionName": "test_compute_invalid_order_throws",
    "className": null,
    "fileName": "/oberbichler_&_EQlib/tests_&_test_problem.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "with pytest.raises(ValueError) as ex:\n    problem.compute(-1)\nassert_equal('order', str(ex.value))\nwith pytest.raises(ValueError) as ex:\n    problem.compute(4)\nassert_equal('order', str(ex.value))\n"
}